name: pull-request
"on":
  pull_request:
    branches:
      - master
  schedule:
    - cron: 57 12 * * *
jobs:
  pyright:
    runs-on: ubuntu-latest
    steps:
      - name: Update CA certificates
        run: sudo update-ca-certificates
      - name: Run 'pyright'
        uses: dycw/action-pyright@latest
        with:
          python-version: "3.13"
          native-tls: true
          token-github: ${{secrets.ACTION_TOKEN}}
          index: https://pypi.queensberryresearch.com/simple
          index-username: qrt
          index-password: ${{secrets.NANODE_PYPI_PASSWORD}}
  pytest:
    env:
      CI: "1"
    name: pytest (${{matrix.os}}, ${{matrix.python-version}}, ${{matrix.resolution}})
    runs-on:
      - ${{matrix.os}}
    steps:
      - name: Update CA certificates
        run: sudo update-ca-certificates
      - name: Run 'pytest'
        uses: dycw/action-pytest@latest
        with:
          python-version: ${{matrix.python-version}}
          sops-age-key: ${{secrets.SOPS_AGE_KEY}}
          resolution: ${{matrix.resolution}}
          native-tls: true
          token-github: ${{secrets.ACTION_TOKEN}}
          index: https://pypi.queensberryresearch.com/simple
          index-username: qrt
          index-password: ${{secrets.NANODE_PYPI_PASSWORD}}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - "3.13"
          - "3.14"
        resolution:
          - highest
          - lowest-direct
    timeout-minutes: 10
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Update CA certificates
        run: sudo update-ca-certificates
      - name: Run 'ruff'
        uses: dycw/action-ruff@latest
        with:
          token-github: ${{secrets.ACTION_TOKEN}}
