name: push
"on":
  push:
    branches:
      - master
jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
      - name: Update CA certificates
        run: sudo update-ca-certificates
      - name: Tag the latest commit
        uses: dycw/action-tag-commit@latest
        with:
          token-github: ${{secrets.ACTION_TOKEN}}
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Update CA certificates
        run: sudo update-ca-certificates
      - name: Build and publish the package
        uses: dycw/action-publish-package@latest
        with:
          native-tls: true
          token-github: ${{secrets.ACTION_TOKEN}}
          username: qrt-bot
          password: ${{secrets.PYPI_GITEA_READ_WRITE_TOKEN}}
          publish-url: https://gitea.qrt:3000/api/packages/qrt/pypi
  publish-nanode:
    runs-on: ubuntu-latest
    steps:
      - name: Update CA certificates
        run: sudo update-ca-certificates
      - name: Build and publish the package
        uses: dycw/action-publish-package@latest
        with:
          token-github: ${{secrets.ACTION_TOKEN}}
          username: qrt
          password: ${{secrets.PYPI_NANODE_PASSWORD}}
          publish-url: https://pypi.queensberryresearch.com
          native-tls: true
